name: Run Postman API Tests

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: newman run "Api Testing Project/Swaggar Petstore.postman_collection.json" -e "Api Testing Project/PetStore Api Testing.postman_environment.json" || true
